version: '3.8'
services:
  mongodb:
    image: mongo:6.0  # Using MongoDB 6.0 for compatibility with PyMongo 4.6.2
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=cda123
    ports:
      - "27017:27017"  # Expose MongoDB port to host
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=cda123
      - ME_CONFIG_MONGODB_URL=mongodb://root:cda123@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=cda123
    ports:
      - "18084:8081"  # Expose Mongo Express web UI
    depends_on:
      - mongodb
    networks:
      - mongo-network
    restart: unless-stopped

networks:
  mongo-network:
    driver: bridge

volumes:
  mongo-data:
